//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan RunningTime { get; set; }
        public double Ratting { get; set; }
        public System.DateTime Establish { get; set; }
        public string image { get; set; }
    
        public virtual MovieType MovieType { get; set; }
    }
}
